COPY INTO OPENSKY_RAW_ETL.RAW.RAW_DATA (raw_data)
FROM @OPENSKY_RAW_ETL.RAW.S3_OPENSKY_STAGE
FILE_FORMAT = (TYPE = 'JSON', STRIP_OUTER_ARRAY = TRUE)
PATTERN = '.*\.json'
ON_ERROR = 'SKIP_FILE'
FORCE = TRUE;